[package]
name = "sneakyterminal"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
crossbeam = "0.8.2"
glam = { version = "0.24.2", features = ["fast-math"] }
nix = { version = "0.27.1", features = ["term"] }
spin_sleep = "1.1.1"
